server:
  port: 8001

spring:
  application:
    name: cloud-consumer-hystic
eureka:
  client:
    register-with-eureka: true
    service-url:
    # 设置与Eureka Server交互的地址  查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/

