server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangyaoyao93/config-repository.git
          #搜索目录
          search-paths:
            - config-repository
          #username: xxxxx
          #password: xxxxxxx
      #读取分值
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/