server:
  port: 9587

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      # 这里可以配置多个
      routes:
        - id: payment_routh # 路由ID，没有规定的规则，但要求全局唯一
          uri: http://localhost:8001
          predicates: # #断言，路径相匹配就进行路由
            # 也可以配置多个
            - Path=/payment/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/